import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.scss'

const roboto = localFont({ src: '../fonts/Roboto-Regular.ttf' })

export const metadata: Metadata = {
  title: process.env.APP_TITLE,
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
